apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jupyterlab-cr
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jupyterlab-crb
subjects:
  - kind: ServiceAccount
    name: jupyterlab-sa
    namespace: jupyterhub
roleRef:
  kind: ClusterRole
  name: jupyterlab-cr
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jupyterlab-sa
  namespace: jupyterhub
